[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "kitty --class kitty-terminal"
class = "kitty-terminal"
size = "80% 95%"

[scratchpads.networkmanager]
command = "kitty --class network -e nmtui"
class = "network"
size = "40% 60%"